<?php

namespace app\models;

use Yii;
use yii\base\Exception;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property int $category_id
 * @property string $name
 * @property string $description
 * @property string $content
 * @property int $active
 * @property int $price
 * @property string $old_price
 * @property string $image
 *
 * @property Category $category
 */
class Product extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id', 'active','main_page', 'price', 'old_price'], 'integer'],
            [['name'], 'required'],
            [['description', 'content'], 'string'],
            [['name'], 'string', 'max' => 255],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
           //['image', 'string'],
            [['image'], 'file', 'extensions' => ['svg', 'jpg', 'png']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Категория',
            'name' => 'Заголовок',
            'description' => 'Описание',
            'content' => '',
            'active' => 'Опубликовать',
            'price' => 'Цена',
            'old_price' => 'Старая цена',
            'main_page'=>'Показывать на главной',
            'image'=>'Загрузите изображение',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    public function getImage(){
        return $this->image;
    }

    /**
     * @return bool
     */
    public function upload()
    {
        if ($this->validate()) {

            try {
                $filename = 'uploads/' . $this->image->baseName . Yii::$app->security->generateRandomString(3) . '.' . $this->image->extension;
            } catch (Exception $e) {
            }

            $this->image->saveAs($filename);
            $this->image = '/' . $filename;

            return true;
        } else {
            return false;
        }
    }



    /*public function upload()
    {
        if ($this->validate()) {
            $this->imageFile->saveAs('uploads/' . $this->imageFile->baseName . '.' . $this->imageFile->extension);
            return true;
        } else {
            return false;
        }
    }*/




    public function beforeSave($insert)
    {
        $this->image = \yii\web\UploadedFile::getInstance($this,'image');
        $this->upload();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
